### PR TITLE
Upgrading thumbs with what's in C2FO Master

### PR DESCRIPTION
**Pull request by nicknisi**
**Reviewers**:
- [x] @doug-martin 
- [ ] @andymoon 

This is to make sure we capture what's in c2fo/master. This is part of the work of switching that repo over to using bower, so it's important to make sure this is up to date

### CODE REVIEW

**Comment by doug-martin** [comment]
Looks good...I'll add a ticket to the refactor to get the thumbs tests up to date

**Comment by nicknisi** [comment]
Sounds good. I'll add one to upgrade thumbs to use grunt 0.4

**Comment by doug-martin** [comment]
[#543](https://honeycomb.jira.com/browse/CFO-543)

**Comment by nicknisi** [comment]
[[544]](https://honeycomb.jira.com/browse/CFO-544)

**Pull request merged**
